### PR TITLE
Add Ubuntu 22.04 to the molecule tests

### PR DESCRIPTION
**Pull request by guenhter**
Solves https://github.com/NVIDIA/ansible-role-nvidia-driver/issues/63

### CODE REVIEW

**Comment by ajdecon** [comment]
The CI test is failing on Ubuntu 22.04 with the NVIDIA CUDA repository with the following message:

```
fatal: [ubuntu-2204-cuda]: FAILED! => {"changed": false, "msg": "No package matching 'cuda-drivers-510' is available"}
```

Checking the [NVIDIA CUDA repos](https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/), it looks like the earliest available driver for Ubuntu 22.04 is in the R515 branch.

Based on the [driver lifecycle page](https://docs.nvidia.com/datacenter/tesla/drivers/#cuda-drivers), R515 is listed as a production driver branch. And checking the Ubuntu repositories, it looks like there are R515 packages available for both `-server` and non-server branches.

Long-story short, I'd suggest you also try updating `nvidia_driver_branch` to 515 in this PR (or a separate one if you prefer). Assuming that checks out in CI, this should be good to merge.

Also, please sign-off your commits according to the guidance from the [DeepOps repo](https://github.com/NVIDIA/deepops/blob/master/CONTRIBUTING.md).

**Comment by guenhter** [comment]
@ajdecon Thx for the feedback. Everything done. Upgraded to 515 and signed-off the commits

**Comment by guenhter** [comment]
@ajdecon  any idea when you will merge this?

**Comment by ajdecon** [comment]
Apologies for the delay! This fell off my radar, but looks good. Will merge.

**Review by ajdecon — APPROVED** [review]

**Comment by guenhter** [comment]
Thx. Appreciate your extremely quick actions.

**Pull request merged**
